### PR TITLE
Adds an overlay to identify easy FigmaSharp files in SolutionExplorer

### PR DESCRIPTION
**Pull request by netonjm**
Figma generated views can be moved in the project, and sometimes when they are in the same directory like other views it is not easy to differentiate.

It would be very useful include a overlay to make clear which are FigmaSharp views. Additionally we could add some sync/unsynch color, because when a file is generated, sometimes because the document changes or a layout name changes can be un synch, and this causes the developer not to understand why this happens.

Red icon color means the element is out of sync / Orange in synch

Fixes https://github.com/microsoft/FigmaSharp/issues/199

image

### CODE REVIEW

**Comment by netonjm** [comment]
@hbons could you create a better overlay here?

**Review by mrward — APPROVED** [review]

**Comment by hbons** [comment]
Sure. what's the difference between the red/orange overlays?

**Comment by netonjm** [comment]
> Sure. what's the difference between the red/orange overlays?

Red means the element is out of synch, probably because the view was removed from the document or the name was changed, so this means it will be not updated

**Comment by netonjm** [comment]
The functionality seems to be working, I created a task for the icons so we can change after merge https://github.com/microsoft/FigmaSharp/issues/351

**Pull request merged**
